### ISSUE TITLE
Describe technologies in project

### ISSUE THREAD

**Issue by kitkat0202** [evansimonross/Fly-in-Soup#54]
### In Charge of:
**Evan:** NYC Health Inspection API, and NYC geocode API
**Jano:**  MapBox API
**Katherine:** Zomato API, Firebase Auth

### Information:
- [ ] About the Tech
- [ ] How it works
- [ ] Why we needed it
- [ ] Most difficult thing about learning the tech

**Comment by evansimonross** [comment]
## DOHMH New York City Restaurant Inspection Results API
- Part of NYC data that publishes the records of the Department of Health and Mental Heath's restaurant inspection results daily. 
- It's a basic database in which each inspection result is logged, along with data about the restaurant, grade (if given) and any violations that were cited.
- We needed it because the health inspection grades were the core concept of our project. This is the data we wanted most!
- Most difficult thing was the inconsistency of the data. For example, some restaurant names were written LIKE THIS and others were Like This. If we searched by restaurant, we had to do two separate API calls to get around this. There were several quirks like these throughout the data.

## NYC Planning Labs GeoSearch API
- A beta project by NYC Planning Labs which takes street address information as input and outputs geographic coordinates
- A query to this API returns a list of possible matches along with their geographic coordinates. 
- In order to display the location of restaurants on a map, we needed to translate the addresses from the Health Inspection database into something Mapbox could understand: geocodes.
- One difficulty we faced was the fact that certain street name conventions are followed by the Health Inspection API and different ones are followed by the GeoSearch API. For example, a restaurant on "E 4th Street" in the DOH database got the Geocode database confused that we didn't input "E 4 Street". So, we scrapped our original plan to pull only the top result from the GeoSearch, and instead we pulled the top ten and found the one in the correct zip code from the results.

**Comment by kitkat0202** [comment]
# Zomato:
[Zomato Documentation](https://developers.zomato.com/documentation)
-    An API that provides information on restaurants
-    You can search for restaurants by name, cuisine, address and geocode
-    This technology was used to query the nearest restaurants by geocode to input into the Health inspection API
-    The most difficult part of this API was to figure out how to create the link to get to the JSON info. It was not provided in the documentation, but fortunately Stockoverflow had the solution

# Firebase Authentication:
[Firebase Auth user database](https://console.firebase.google.com/project/fly-in-soup/authentication/users)
[Firebase realtime database](https://console.firebase.google.com/project/fly-in-soup/database/fly-in-soup/data)
-    This technology allows users to create an account on our site
-    This allows users to save their favorite restaurant on their account and allow then access whenever they log in
-    The log in feature first requires the users to entere an email. Then firebase will check all the email addresses in the auth database to see if it exsists. If it does then it will prompt you for your password if the email foes not exsist then it will ask you to create an account.
-    The most difficult part of this technology was learining to to link the auth database with the realtime database to save all the favorites.

**Comment by Jroze88** [comment]
### MapBox API

- MapBox API generates an interactive map for embedding in web applications and displaying location-based information and user input.

- Allows web applications to visualize locations on an accurate, real-world map from any JavaScript/user information.

- MapBox API made showing information relevant to a User's area much easier. It provided a single window to show user location, local restaurant locations, restaurant grades and directions at a glance in a way that was easy to understand. The MapBox API provided a map with more style options and less rigid implementation for our purposes than Google Maps.

- Most difficult part of learning the MapBox API was reading through the documentation to understand how to take many different types of information provided by group mates from various other API's including restaurant locations, user location, geocoding information and restaurant grades and implementing it in a way that creates a simple, adaptable, 'single-click' experience for the user regardless of their location.
